// Generated by xecudac for Intel Arc Xe2
#include "xecuda.h"
#include <stdio.h>

__global__ void myCudaKernel(float* data, int n) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        data[idx] *= 2.0f;
    }
}

int main() {
    int n = 1024;
    size_t bytes = n * sizeof(float);

    float* d_data;
    xeCudaMalloc((void**)&d_data, bytes);

    XECUDA_LAUNCH(myCudaKernel, 1, 1024, d_data, n);
    xeCudaDeviceSynchronize();

    xeCudaFree(d_data);
    printf("CUDA Kernel executed successfully on Intel Arc!\n");
    return 0;
}
