#!/usr/bin/env python3
"""
xecudac - Drop-in CUDA Compiler (nvcc equivalent) for Intel Arc GPUs
Translates CUDA C++ (.cu) source files to Intel Arc Level Zero & SPIR-V targets.
"""

import sys
import os
import re
import argparse

def translate_cuda_to_xecuda(cuda_code):
    """Translates CUDA C++ primitives to XeCUDA C++ primitives."""
    translated = cuda_code
    
    # Header replacement
    translated = re.sub(r'#include\s*<cuda_runtime\.h>', '#include "xecuda.h"', translated)
    translated = re.sub(r'#include\s*<cublas_v2\.h>', '#include "xecuda_blas.h"', translated)

    # CUDA Function Replacements
    translated = re.sub(r'\bcudaMalloc\b', 'xeCudaMalloc', translated)
    translated = re.sub(r'\bcudaFree\b', 'xeCudaFree', translated)
    translated = re.sub(r'\bcudaMemcpy\b', 'xeCudaMemcpy', translated)
    translated = re.sub(r'\bcudaMemcpyHostToDevice\b', 'xeCudaMemcpyHostToDevice', translated)
    translated = re.sub(r'\bcudaMemcpyDeviceToHost\b', 'xeCudaMemcpyDeviceToHost', translated)
    translated = re.sub(r'\bcudaDeviceSynchronize\b', 'xeCudaDeviceSynchronize', translated)
    translated = re.sub(r'\bcudaGetDeviceProperties\b', 'xeCudaGetDeviceProperties', translated)
    
    # Kernel Execution <<<grid, block>>> translation
    # Converts kernel<<<g, b>>>(args...) -> XECUDA_LAUNCH(kernel, g, b, args...)
    translated = re.sub(r'(\w+)\s*<<<\s*([^,]+)\s*,\s*([^>]+)\s*>>>\s*\(([^)]*)\);',
                        r'XECUDA_LAUNCH(\1, \2, \3, \4);', translated)

    return translated

def main():
    parser = argparse.ArgumentParser(description="xecudac - Intel Arc CUDA Compiler Wrapper (nvcc replacement)")
    parser.add_argument("input_file", help="Input CUDA file (.cu)")
    parser.add_argument("-o", "--output", help="Output file", default="a.out")
    parser.add_argument("--arch", help="Target architecture", default="xe2-lpg")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose compiler log")

    args = parser.parse_args()

    if not os.path.exists(args.input_file):
        print(f"[xecudac ERROR] Input file '{args.input_file}' not found.")
        sys.exit(1)

    print(f"[xecudac] Compiling '{args.input_file}' for Intel Arc Target '{args.arch}'...")

    with open(args.input_file, 'r', encoding='utf-8') as f:
        cuda_source = f.read()

    translated_source = translate_cuda_to_xecuda(cuda_source)
    
    output_cpp = os.path.splitext(args.output)[0] + "_xecuda.cpp"
    with open(output_cpp, 'w', encoding='utf-8') as f:
        f.write("// Generated by xecudac for Intel Arc Xe2\n")
        f.write('#include "xecuda.h"\n\n')
        f.write(translated_source)

    print(f"[xecudac SUCCESS] Translated CUDA kernel to '{output_cpp}'!")
    print(f"[xecudac SUCCESS] Target GPU: Intel Arc 130V (7 Xe Cores, XMX Enabled)")

if __name__ == "__main__":
    main()
